---

- block:

  - name: Check if bridge-nf-call-iptables key exists
    command: "sysctl net.bridge.bridge-nf-call-iptables"
    failed_when: false
    changed_when: false
    register: sysctl_bridge_nf_call_iptables

  - name: Enable bridge-nf-call tables
    sysctl:
      name: "{{ item }}"
      state: present
      sysctl_file: "{{ sysctl_file_path }}"
      value: 1
      reload: yes
    when: sysctl_bridge_nf_call_iptables.rc == 0
    loop:
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-arptables
      - net.bridge.bridge-nf-call-ip6tables

  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  become_method: sudo

- name: Join node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
