
- name: Pin package version for RedHat with versionlock yum plugin
  when: ansible_os_family == 'RedHat'
  block:
  - name: install yum-version-lock plugin
    yum:
      name: yum-plugin-versionlock
      state: present

  - name: Lock k8s components to targeted versions
    loop: "{{ kubernetes_packages }}"
    shell: yum versionlock add {{ item.name }}
    register: versionlock_result
    changed_when: "'versionlock added: 1' in versionlock_result.stdout_lines"
    args:
      warn: false
  
- name: Add Kubernetes apt preferences file to pin a version.
  when: ansible_os_family == 'Debian'
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: 0644
