---
- name: Ensure procps is installed.
  package:
    name: "{{ procps_package }}"
    state: present
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

# See: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
- name: Ensure relevant kernel module is enabled
  modprobe:
    name: br_netfilter
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Check if kernel parameter file exists
  ansible.builtin.stat:
    path: /etc/sysctl.d/k8s.conf
  register: kubernetes_kernel_parameter_file

- name: Create kernel parameter file if it doesn't exist
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
    owner: root
    group: root
    mode: 0644
  when: kubernetes_kernel_parameter_file.stat.exists is falsy

- name: Persist kernel modules after reboot
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
  loop:
    - "net.bridge.bridge-nf-call-iptables = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.ipv4.ip_forward = 1"

- name: Let iptables see bridged traffic.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10
